config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'statics/top'
  get 'statics/second'
  get 'statics/third'
  get 'statics/plugin'

  root 'statics#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/statics_controller.rb
# frozen_string_literal: true

class StaticsController < ApplicationController
  protect_from_forgery except: :plugin

  def top; end

  def second; end

  def third; end

  def plugin
    cookies[:fanp_chatlink_conditions] = condition_open_modal_json
    render :plugin
  end

  def banner
    send_file 'https://placehold.jp/300x150.png', type: 'image/png'
  end

  private

  def condition_open_modal_json
    {
      paterns: [
        {
          path_regexp: '^/statics/top',
          page_chatlinks: {
            banner: {
              img_url: 'https://placehold.jp/300x150.png'
            },
            modal: {
              conditions: {
                ref_regex: '/statics/second'
              }
            }
          }
        },
        {
          path_regexp: '^/statics/second',
          page_chatlinks: {
            banner: {
              img_url: 'https://placehold.jp/150x150.png'
            },
            modal: {
              conditions: {
                wait_for: 3
              }
            }
          }
        },
        {
          path_regexp: '^/statics/third',
          page_chatlinks: {
            modal: {
              conditions: {
                transition_count: 3
              }
            }
          }
        }
      ]
    }.to_json
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/statics_helper.rb
# frozen_string_literal: true

module StaticsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OpenModalFromUserEvent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/statics/plugin.js.erb
var cookiesArray = document.cookie.split('; ');
console.log(cookiesArray);


const jsonParseCookieVal = cookie_key => {
  var cookie_val = decodeURIComponent(((document.cookie + ';').match(cookie_key + '=([^¥S;]*)') || [])[1])
  if (cookie_val == 'undefined') {
    return undefined;
  } else {
    return JSON.parse(cookie_val);
  }
}


//get condition for current page *************

// 特定のcookieのkeyからJSONをparseする
let jsonVal = jsonParseCookieVal('fanp_chatlink_conditions')
console.log(jsonVal);

var currentUrl = location.href;
var currentPath = location.pathname;

// forEeach がBreakできないそうなので someを使用
jsonVal.paterns.some(function(element){
  var regex = new RegExp(element.path_regexp);
  var isCurrent = regex.test(currentPath);
  if (isCurrent) {
    currentChatlinks = element.page_chatlinks
    // パターンにマッチした瞬間にループ抜ける（本来の使い方とは若干ずれるらしい）
    // 他にも書き方あるので要検討
    return true;
  }
})

console.log(currentChatlinks);


//transition count func *************

var transitionVal = jsonParseCookieVal('transition_count');
var transitionCount = !transitionVal ? 0 : Number(transitionVal);

var currentHost = location.protocol + '//' + location.host;
var referrerUrl = document.referrer;
var hostRegex = new RegExp('^' + currentHost);
isSameHost = hostRegex.test(referrerUrl);
if (isSameHost) {
  transitionCount += 1;
  document.cookie = `transition_count=${transitionCount}`;
  console.log('同じところで遷移');
} else {
  console.log('外部から遷移');
}

console.log('現在の遷移数', transitionCount)


// modal dom *************

var closeContentArr = [
      "<div class='fanp-modal-overLay fanp-modal-close'>",
      "モーダル",
      "</div>"
    ];
var modalTag = document.createElement('div');
modalTag.innerHTML = closeContentArr.join('');
modalTag.id = 'fanp-modal';


// open modal func *************

const statusCondProcessExec = isExeced => {
  isExeced ? console.log('もう実行できない') : console.log('まだ実行できる')
}

function openModal() {
  if (isCondProcessExec == true) {
    console.log('1度しか実行できません')
    return;
  }
  document.body.appendChild(modalTag);
  isCondProcessExec = true;
}

var refConditionFunc = function(conditionVal) {
  console.log('refです');
  openModal();
}
var waitForConditionFunc = function(conditionVal) {
  console.log('wait_for です');
  setTimeout(() => {
    openModal();
    statusCondProcessExec(isCondProcessExec);
  }, conditionVal * 1000);
}
var transitionCountConditionFunc = function(conditionVal) {
  console.log('transition_countです');
  if (transitionCount >= conditionVal) {
    openModal();
  }
}

var isCondProcessExec = false

var conditionProcess = function(condition) {
  switch(condition[0]) {
    case 'ref':
      refConditionFunc(condition[1]);
      break;
    case 'wait_for':
      waitForConditionFunc(condition[1]);
      break;
    case 'transition_count':
      transitionCountConditionFunc(condition[1]);
  }
}

if (!currentChatlinks.modal) {
  console.log('ないで！！！');
} else {
  conditionProcess(Object.entries(currentChatlinks.modal.conditions)[0])
}

statusCondProcessExec(isCondProcessExec)


// banner open func

app/views/statics/second.html.erb
<h1>Statics#second</h1>
<p><%= link_to 'thirdへ', statics_third_path %></p>
<p><%= link_to 'topへ', statics_top_path %></p>


<script id="open-modal-plugin" src="http://localhost:3000/statics/plugin.js" ></script>

app/views/statics/third.html.erb
<h1>Statics#third</h1>

<p><%= link_to 'secondへ', statics_second_path %></p>
<p><%= link_to 'topへ', statics_top_path %></p>



<script id="open-modal-plugin" src="http://localhost:3000/statics/plugin.js" ></script>

app/views/statics/top.html.erb
<h1>Statics#top</h1>

<p><%= link_to 'secondへ', statics_second_path %></p>
<p><%= link_to 'thirdへ', statics_third_path %></p>

<div>
  <h3>バナー</h3>
  <a href=''><img id='fanp-banner-img-tag' src='' alt=''></a>
</div>

<script id="open-modal-plugin" src="http://localhost:3000/statics/plugin.js" ></script>